### ISSUE TITLE
Adding new default helpers

### ISSUE THREAD

**Issue by MI53RE** [jsreport/jsreport-sample-template#4]
Hi Jsreport team!

I've been using Jsreport for a while, mainly with handlebars, and did generated some conditionals (based on the `if else`) global helpers I though that could be nice to share, either by letting them on the sample helpers or maybe by making them fully integrated with jsreport.

I wanted to now if you do think it could be interesting and, if yes, where should I look to implement it for a PR ?

**Comment by pofider** [comment]
Hi,

nice!
How do the helpers look like, do they have meaning general even without jsreport?
If this is true, I would recommend creating your own repository and publish it to npm.
Then jsreport users can easily `npm i yourhelpers` and `require('yourhelpers')` in jsreport.
Similiar to this
https://github.com/helpers/handlebars-helpers

**Comment by MI53RE** [comment]
well I never did notice this package, maybe beacuse I didn't had the need of something this powefull, the idea here was to provide a very basic set of helpers that would resolve many common task that handlebars cannot by default.

while maybe it can be of use outside of jsreport, I do think it is for the best not having to crawl under external extension. Also make a whole repository for a single file Here is the list of what I was proposing, let me know if you still think that it would be better outside of Jsreport.

```javascript
/**
 * Check if all values are truthy
 */
function ifAnd(...parameters) { /*...*/ }

/**
 * Check if at least one value is truthy
 */
function ifOr(...parameters) { /*...*/ }

/**
 * Check if exactly one value is truthy
 */
function ifXor(...parameters) { /*...*/ }

/**
 * Check if first value is equals to another within several values
 */
function ifEither(...parameters) { /*...*/ }

/**
 * Check if first value is not equals to another within several values
 */
function ifNeither(...parameters) { /*...*/ }

/**
 * Check if value is falsy
 */
function ifNot(inputValue, options) { /*...*/ }

/**
 * Check if first value is equals to second value
 */
function ifEquals(value1, value2, options) { /*...*/ }

/**
 * Check if first value is less than second value
 */
function ifLessThan(value1, value2, options) { /*...*/ }

/**
 * Check if first value is more than second value
 */
function ifMoreThan(value1, value2, options) { /*...*/ }

/**
 * Check if first value is less than or equals to second value
 */
function ifLessOrEquals(value1, value2, options) { /*...*/ }

/**
 * Check if first value is more than or equals to second value
 */
function ifMoreOrEquals(value1, value2, options) { /*...*/ }

/**
 * Check if first value is different to second value
 */
function ifNotEquals(value1, value2, options) { /*...*/ }

/**
 * Must be used in an #each loop
 * every "value" iteration return true
 */
function ifIndexAt(value, index, options) { /*...*/ }

/**
 * Must be used in an #each loop
 * every "value" + "offset" iteration return true
 * example : 5 + -3 = 2 so every 2 iteration return true
 */
function ifIndexAtOffset(value, index, offset, options) { /*...*/ }

/**
 * Check if value match regexp
 */
function ifRegexp(regexp, value, options) { /*...*/ }

/**
 * Add a new page to the document, work only if there is a previous content in the page (visible or not)
 * must be used with this exact syntax in the html : {{{newPage}}}
 */
function newPage() {
    return '<div style="display: block; page-break-before: always;"></div>';
}
```

In any case, thank you for your attention 😃 !

**Comment by pofider** [comment]
I think the sample template is not a good place for it.

You can create a custom jsreport extension that add this to helpers automatically.
Or as I originally suggested it can be just a normal npm package that users require from helpers.
It is up to you.

**Comment by MI53RE** [comment]
Ok, I'll proceed with one of those two options then

Thank you again for your time!

**Comment by pofider** [comment]
Great.
I am closing this one here.
